on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: security.yaml

permissions: read-all

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::oysteR, any::dplyr

      - name: Scan dependencies
        run: |
          audit <- oysteR::audit_renv_lock(verbose = TRUE)

          # If at least one vulnerability is found, print information and throw error
          if (sum(audit$no_of_vulnerabilities) > 0) {

            vulnerable_packages <-
              audit |>
              dplyr::filter(no_of_vulnerabilities > 0)

            vulnerable_packages |>
              dplyr::select(package, version) |>
              print()

            print("See link(s) for more information: ")
            for (url in vulnerable_packages$reference) {
              print(paste0("- ", url))
            }
          }
        shell: Rscript {0}
